# archived from docker-compose.yml
# image: neo4j:latest
# image: neo4j:enterprise-bullseye
# image: neo4j:ubi9 #https://hub.docker.com/layers/library/neo4j/ubi9/images/sha256-7e3f6b03f983c132eb594901aeed538331c1d3cd75fef09f0f5a3de150d4e6d5
# image: neo4j:enterprise-ubi9 #https://hub.docker.com/layers/library/neo4j/enterprise-ubi9/images/sha256-ea33aab418688b5f11cfb035b129b01465a4a0cfdd662585520533a762f67d65
# image: neo4j:5.26.8-enterprise-ubi9 #https://hub.docker.com/layers/library/neo4j/5.26.8-enterprise-ubi9/images/sha256-278e58c04f5b46738a115379934c189d5fd08ffa54b386f68658877d9cc8c8af
# -> this ver. worked with neo4j-admin import

# FROM neo4j:5.26.8-enterprise-ubi9
# still working OK, used for the longest time
# -> this ver. worked with neo4j-admin import

FROM neo4j:5.26.12-enterprise-ubi9
# latest version OK
