# version: "3.7"
services:
  # MySQL service
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    # where we put environment variables. Put in .gitignore
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PW" ]
      # 'localhost' or 'db' works just the same
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - 4001:3306

    # command: echo "ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'my173';" > /home/eli.sql
    # command: mysql -uroot -pmy173 Employees < /home/eli.sql
    # entrypoint: entrypoint

  # Apache and PHP service
  web:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    # Below was working. I needed it if I want to restart Apache in terminal mode in Docker.
    environment:
      APACHE_RUN_DIR: /etc/apache2
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2/apache2.pid
      APACHE_LOG_DIR: /var/log/apache2
    ports:
      - "81:80"
    volumes:
      - ${WEBROOT_PATH}:/var/www/html
      - ${APACHE_LOGS}:/var/log/apache2
      - ${APACHE_CONFIG}:/etc/apache2/sites-enabled
      - usr_local:/usr/local
      - usr_lib:/usr/lib
      # this is the path where php binary is located 
      # /usr/local/bin/php
      # /usr/lib/aarch64-linux-gnu/libxml2.so.2.9.14
      # find /path/ -type f -name file-to-search

    links:
      - db
    # https://geshan.com.np/blog/2024/02/docker-compose-depends-on/

  # Jenkins service
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile    
    # restart: on-failure
    env_file: ./.env

    # volumes_from:
    #   - web:rw

    volumes:
      # - ${JENKINS_HOME}:/var/jenkins_home
      - ./jenkins-home:/var/jenkins_home
      - ${WEBROOT_PATH}:/webroot
      - usr_local:/usr_local
      - usr_lib:/usr_lib
    links:
      - web

    ports:
      - 8081:8080
      - 50000:50000
    environment:
      JAVA_OPTS: "-Dhudson.footerURL=http://dev_connectors.eol.org -Djava.util.logging.config.file=/var/jenkins_home/log.properties"
      # - "-Dhudson.footerURL=http://dev_connectors.eol.org"
      # - "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"

volumes:
  usr_local:
  usr_lib:
    # external: true

# ============================================== copied template
    # image: mysql:8.0.12
    # image: mysql:8.4.3-oraclelinux9

    # command: mysqld --default-authentication-plugin=mysql_native_password
    #  -> this gives error

    # command: --default-authentication-plugin=mysql_native_password
    # command: mysql -uroot -pmyXXX --default-authentication-plugin=mysql_native_password

  # database:
  #   image: mysql:8.0.40-debian
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
    # environment:
    #   MYSQL_ROOT_PASSWORD: <root_password>
    #   MYSQL_DATABASE: <database_name>
    #   MYSQL_USER: <user_name>
    #   MYSQL_PASSWORD: <user_password>
    # ports:
    #   - 3306:3306


  # db:
  #   build:
  #     context: ./mysql
  #     dockerfile: Dockerfile
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_ROOT_HOST=%
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
