# version: "3.7"
services:
  web:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    # depends_on:
    #   - db

    # Below was working. I needed it if I want to restart Apache in terminal mode in Docker.
    environment:
      APACHE_RUN_DIR: /etc/apache2
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2/apache2.pid
      APACHE_LOG_DIR: /var/log/apache2
      
    ports:
      - "81:80"
    volumes:
      - ${WEBROOT_PATH}:/var/www/html
      - ${APACHE_LOGS}:/var/log/apache2
      - ${APACHE_CONFIG}:/etc/apache2/sites-enabled
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile

    restart: unless-stopped

    # where we put environment variables. Put in .gitignore
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - 4001:3306

# ============================================== copied template
    # image: mysql:8.0.12
    # image: mysql:8.4.3-oraclelinux9

    # command: mysqld --default-authentication-plugin=mysql_native_password
    #  -> this gives error

    # command: --default-authentication-plugin=mysql_native_password
    # command: mysql -uroot -pmyXXX --default-authentication-plugin=mysql_native_password

  # database:
  #   image: mysql:8.0.40-debian
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
    # environment:
    #   MYSQL_ROOT_PASSWORD: <root_password>
    #   MYSQL_DATABASE: <database_name>
    #   MYSQL_USER: <user_name>
    #   MYSQL_PASSWORD: <user_password>
    # ports:
    #   - 3306:3306


  # db:
  #   build:
  #     context: ./mysql
  #     dockerfile: Dockerfile
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_ROOT_HOST=%
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
