services:
  # =================== MySQL service ===================
  db:
    # where we put environment variables. Put in .gitignore
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
    build:
      context: ./mysql
      args:
        MRP_FROM_COMPOSE: ${MYSQL_ROOT_PW}
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PW" ]
      # 'localhost' or 'db' works just the same
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - ${MYSQL_PORTS} # 4001:3306

  # =================== Apache and PHP service ===================
  web:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    # restart: always
    depends_on:
      db:
        condition: service_healthy
    # Below was working. I needed it if I want to restart Apache in terminal mode in Docker.
    environment:
      APACHE_RUN_DIR: /etc/apache2
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2/apache2.pid
      APACHE_LOG_DIR: /var/log/apache2
      TARGET_PATH: ${WEBROOT_PATH}
      MY_ENV: ${MY_ENVIRONMENT}
    volumes:
      - ${WEBROOT_PATH}:/var/www/html
      - ${APACHE_LOGS}:/var/log/apache2
      - ${VOLUMES_LOCAL}:/Volumes
      - ${EXTRA_PATH}:/extra
    command: ${PWD}/apache-php/docker-entrypoint_${MY_ENVIRONMENT}.sh #works OK
    # entrypoint: ${PWD}/apache-php/docker-entrypoint.sh #works OK as well
    ports:
      - ${WEB_PORTS} # 81:80
    links:
      - db
    # Sol'n so u can curl local webserver from host. 
    # Use 'host.docker.internal' instead of 'localhost' in PHP script.
    # https://medium.com/@gladevise/accessing-the-hosts-localhost-from-inside-a-docker-container-c5935e275953
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  # =================== Jenkins service ===================
  jenkins:
    env_file: ./.env
    build:
      args:
        JENKINS_HOME_FROM_COMPOSE: "" #${JENKINS_HOME}
        JENKINS_TMP_FROM_COMPOSE: ${JENKINS_TMP}
      context: ./jenkins
      dockerfile: Dockerfile
    # restart: on-failure
    volumes:
      - ${PWD}/jenkins_home:/var/jenkins_home
      # -> works OK

      # - ${JENKINS_HOME}:/var/jenkins_home
      # -> rw permissions error

      # - ${WEBROOT_PATH}:/webroot
      - ${WEBROOT_PATH}:/var/www/html

      - ${JENKINS_TMP}:/jenkins_tmp
      # - ${PWD}/jenkins_tmp:/jenkins_tmp     # -> works OK also

      - ${VOLUMES_LOCAL}:/Volumes
      - ${EXTRA_PATH}:/extra

    links:
      - web
      - db
    ports:
      - ${JENKINS_PORTS} # 8081:8080
      - 50000:50000 # Jenkins default port for communication

    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

    environment:
      JAVA_OPTS: "-Dhudson.footerURL=http://dev_connectors.eol.org -Djava.util.logging.config.file=/var/jenkins_home/log.properties -Djava.io.tmpdir=/jenkins_tmp"
    # network_mode: "bridge"
    # volumes:
    #   jenkins_home:


    # Solution: for sometimes --build get corrupted.
    # sudo rm  ~/.docker/config.json 
    # Rerun restart 

    # =================== END ===================