services:
  # =================== Apache and PHP service ===================
  web:
    env_file:
      - ./.env
    volumes:
      # - ${VOLUMES_LOCAL}:/Volumes #for development only
      - /Volumes:/Volumes #for development only
  # =================== Jenkins service ===================
  jenkins:
    env_file: ./.env
    volumes:
      # - ${VOLUMES_LOCAL}:/Volumes #for development only
      - /Volumes:/Volumes #for development only

